[package]
name = "thales-cli"
edition.workspace = true
version.workspace = true
license.workspace = true

[dependencies]
clap.workspace = true
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true
anyhow = "1.0"
polars = { version = "0.42.0", features = ["lazy", "dtype-datetime", "random", "strings"] }
tokio.workspace = true
contracts = { path = "../contracts" }
strategies = { path = "../strategies" }
alpaca-provider = { path = "../providers/alpaca" }
kraken-provider = { path = "../providers/kraken" }

[dev-dependencies]
assert_cmd = "2"
tempfile = "3"
mockito = "1"
