use std::{
    fs,
    path::PathBuf,
    process,
    time::{SystemTime, UNIX_EPOCH},
};

use alpaca_provider::{AlpacaClient, AlpacaConfig};
use clap::{Parser, Subcommand};
use contracts::{Bar, BarSeries, EnvelopeStatus, ExecutionResult, ResponseEnvelope, TradeIntent};
use kraken_provider::{KrakenClient, KrakenConfig};
use serde::Serialize;
use serde_json::json;
use thiserror::Error;

mod analysis;

#[derive(Debug, Parser)]
#[command(name = "thales-cli", version, about = "Agent trading toolkit CLI")]
struct Cli {
    #[command(subcommand)]
    command: Commands,
}

#[derive(Debug, Subcommand)]
enum Commands {
    FetchMarketData {
        #[arg(long)]
        provider: String,
        #[arg(long)]
        symbol: String,
        #[arg(long)]
        timeframe: String,
    },
    NormalizeBars {
        #[arg(long)]
        input: PathBuf,
    },
    GenerateTradeIntent {
        #[arg(long)]
        market: String,
        #[arg(long)]
        symbol: String,
        #[arg(long)]
        side: String,
        #[arg(long)]
        size_hint: String,
        #[arg(long)]
        confidence: f64,
    },
    ValidateIntent {
        #[arg(long)]
        input: PathBuf,
    },
    ExecuteIntent {
        #[arg(long)]
        provider: String,
        #[arg(long)]
        input: PathBuf,
    },
    AnalyzeMarket {
        #[arg(long)]
        input: PathBuf,
    },
}

fn main() {
    let cli = Cli::parse();
    match run(cli.command) {
        Ok(output) => {
            println!("{output}");
        }
        Err(err) => {
            println!("{}", error_envelope(vec![err.to_string()]));
            process::exit(1);
        }
    }
}

fn run(command: Commands) -> Result<String, CliError> {
    match command {
        Commands::FetchMarketData {
            provider,
            symbol,
            timeframe,
        } => {
            let now = now_unix_ms()?;
            let market = infer_market(&provider);
            // Generate 50 simulated bars
            let mut bars = Vec::new();
            let mut price = 100.0;
            for i in 0..50 {
                let time = now - (50 - i) * 60 * 1000;
                let change = (i as f64).sin() + 0.5; // Deterministic wave
                let open = price;
                let close = price + change;
                let high = open.max(close) + 0.5;
                let low = open.min(close) - 0.5;
                price = close;
                bars.push(Bar {
                    symbol: symbol.clone(),
                    market: market.clone(),
                    timeframe: timeframe.clone(),
                    timestamp_unix_ms: time,
                    open,
                    high,
                    low,
                    close,
                    volume: 10_000.0 + (i as f64) * 100.0,
                });
            }

            let series = BarSeries {
                schema_version: "v0".to_string(),
                bars,
            };
            ok_envelope(series)
        }
        Commands::NormalizeBars { input } => {
            let raw = fs::read_to_string(&input)?;
            let mut series: BarSeries = match serde_json::from_str::<ResponseEnvelope<BarSeries>>(&raw) {
                Ok(envelope) => envelope.data.ok_or(CliError::Validation("Envelope has no data".to_string()))?,
                Err(_) => serde_json::from_str::<BarSeries>(&raw)?
            };
            series.bars.sort_by_key(|bar| bar.timestamp_unix_ms);
            ok_envelope(series)
        }
        Commands::GenerateTradeIntent {
            market,
            symbol,
            side,
            size_hint,
            confidence,
        } => {
            let intent = TradeIntent {
                intent_id: format!("{market}:{symbol}:{side}:v0"),
                market,
                symbol,
                side,
                size_hint,
                confidence,
                horizon: "1h".to_string(),
                rationale: "generated by thales-cli".to_string(),
                invalidation: "manual review".to_string(),
                schema_version: "v0".to_string(),
            };
            ok_envelope(intent)
        }
        Commands::ValidateIntent { input } => {
            let intent: TradeIntent = read_json_file(&input)?;
            let errors = validate_intent(&intent);
            if errors.is_empty() {
                ok_envelope(json!({ "valid": true }))
            } else {
                Err(CliError::Validation(errors.join("; ")))
            }
        }
        Commands::ExecuteIntent { provider, input } => {
            let intent: TradeIntent = read_json_file(&input)?;
            let errors = validate_intent(&intent);
            if !errors.is_empty() {
                return Err(CliError::Validation(errors.join("; ")));
            }

            let result = execute_by_provider(&provider, &intent)?;
            ok_envelope(result)
        }
        Commands::AnalyzeMarket { input } => {
            let raw = fs::read_to_string(&input)?;
            let series: BarSeries = match serde_json::from_str::<ResponseEnvelope<BarSeries>>(&raw) {
                Ok(envelope) => envelope.data.ok_or(CliError::Validation("Envelope has no data".to_string()))?,
                Err(_) => serde_json::from_str::<BarSeries>(&raw)?
            };

            let analysis = analysis::analyze(&series);
            ok_envelope(analysis)
        }
    }
}

fn infer_market(provider: &str) -> String {
    match provider {
        "alpaca" => "equities".to_string(),
        "kraken" => "crypto".to_string(),
        _ => "unknown".to_string(),
    }
}

fn execute_by_provider(provider: &str, intent: &TradeIntent) -> Result<ExecutionResult, CliError> {
    match provider {
        "alpaca" => {
            let cfg =
                AlpacaConfig::from_env().map_err(|err| CliError::Provider(err.to_string()))?;
            let client = AlpacaClient::new(cfg);
            client
                .execute_intent(intent)
                .map_err(|err| CliError::Provider(err.to_string()))
        }
        "kraken" => {
            let cfg =
                KrakenConfig::from_env().map_err(|err| CliError::Provider(err.to_string()))?;
            let client = KrakenClient::new(cfg);
            client
                .execute_intent(intent)
                .map_err(|err| CliError::Provider(err.to_string()))
        }
        other => Err(CliError::Validation(format!(
            "unsupported provider: {other}"
        ))),
    }
}

fn validate_intent(intent: &TradeIntent) -> Vec<String> {
    let mut errors = Vec::new();
    if intent.schema_version != "v0" {
        errors.push("schema_version must be v0".to_string());
    }
    if intent.symbol.trim().is_empty() {
        errors.push("symbol must not be empty".to_string());
    }
    if intent.side != "buy" && intent.side != "sell" {
        errors.push("side must be buy or sell".to_string());
    }
    if !(0.0..=1.0).contains(&intent.confidence) {
        errors.push("confidence must be in [0, 1]".to_string());
    }
    errors
}

fn read_json_file<T>(path: &PathBuf) -> Result<T, CliError>
where
    T: serde::de::DeserializeOwned,
{
    let raw = fs::read_to_string(path)?;
    let parsed = serde_json::from_str::<T>(&raw)?;
    Ok(parsed)
}

fn ok_envelope<T>(data: T) -> Result<String, CliError>
where
    T: Serialize,
{
    let envelope = ResponseEnvelope {
        status: EnvelopeStatus::Ok,
        errors: Vec::<String>::new(),
        warnings: Vec::<String>::new(),
        data: Some(data),
    };
    Ok(serde_json::to_string(&envelope)?)
}

fn error_envelope(errors: Vec<String>) -> String {
    let envelope = ResponseEnvelope::<serde_json::Value> {
        status: EnvelopeStatus::Error,
        errors,
        warnings: Vec::<String>::new(),
        data: None,
    };
    serde_json::to_string(&envelope).unwrap_or_else(|_| {
        "{\"status\":\"error\",\"errors\":[\"failed to serialize error envelope\"],\"warnings\":[],\"data\":null}"
            .to_string()
    })
}

fn now_unix_ms() -> Result<i64, CliError> {
    Ok(SystemTime::now()
        .duration_since(UNIX_EPOCH)
        .map_err(|err| CliError::Provider(format!("system clock error: {err}")))?
        .as_millis() as i64)
}

#[derive(Debug, Error)]
enum CliError {
    #[error("io error: {0}")]
    Io(#[from] std::io::Error),
    #[error("json error: {0}")]
    Json(#[from] serde_json::Error),
    #[error("validation error: {0}")]
    Validation(String),
    #[error("provider error: {0}")]
    Provider(String),
}
