use anyhow::Result;
use async_trait::async_trait;
use polars::prelude::*;
use serde::{Deserialize, Serialize};

/// The intent of a signal.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum SignalType {
    /// Enter a new position.
    Entry,
    /// Close an existing position.
    Exit,
    /// Add to an existing position.
    ScaleIn,
    /// Reduce an existing position.
    ScaleOut,
}

/// The category of a trading strategy.
///
/// This helps in classifying strategies for portfolio management and signal filtering.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum StrategyType {
    MeanReversion,
    TrendFollowing,
    Momentum,
    Breakout,
}

/// A raw trading signal generated by a strategy.
///
/// Signals are the output of strategy execution on a `DataFrame`. They are
/// later converted into `TradeIntent`s by the CLI.
///
/// # Examples
///
/// ```rust
/// use strategies::strategy::{Signal, SignalType};
///
/// let signal = Signal {
///     signal_type: SignalType::Entry,
///     symbol: "BTCUSD".to_string(),
///     side: "buy".to_string(),
///     size_hint: "0.1".to_string(),
///     confidence: 0.8,
///     stop_loss: Some(49000.0),
///     take_profit: Some(51000.0),
///     reason: "Golden Cross".to_string(),
///     timestamp_ms: 1622505600000,
/// };
///
/// assert_eq!(signal.side, "buy");
/// ```
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct Signal {
    /// The type of action to take.
    pub signal_type: SignalType,
    /// The symbol involved.
    pub symbol: String,
    /// The side of the trade ("buy" or "sell").
    pub side: String,
    /// A suggestion for position sizing (e.g., "100" shares, "0.1" BTC, or "max").
    pub size_hint: String,
    /// A confidence score [0.0, 1.0].
    pub confidence: f64,
    /// Recommended stop loss level.
    #[serde(default)]
    pub stop_loss: Option<f64>,
    /// Recommended take profit level.
    #[serde(default)]
    pub take_profit: Option<f64>,
    /// Human-readable reason for the signal.
    pub reason: String,
    /// The timestamp of the signal in milliseconds.
    pub timestamp_ms: i64,
}

/// The core trait that all trading strategies must implement.
///
/// Strategies are stateless in execution but may carry configuration state.
/// They take a Polars `DataFrame` as input and return a vector of `Signal`s.
///
/// # Examples
///
/// ```rust
/// use strategies::strategy::{Strategy, Signal, SignalType, StrategyType};
/// use async_trait::async_trait;
/// use polars::prelude::*;
/// use anyhow::Result;
///
/// struct SimpleMovingAverage;
///
/// #[async_trait]
/// impl Strategy for SimpleMovingAverage {
///     fn name(&self) -> &str { "SMA" }
///     fn strategy_type(&self) -> StrategyType { StrategyType::TrendFollowing }
///
///     async fn generate_signals(&self, data: &DataFrame) -> Result<Vec<Signal>> {
///         // Example: Get the last closing price
///         let close = data.column("close")?.f64()?;
///         let last_price = close.get(close.len() - 1).unwrap_or(0.0);
///         let last_ts = data.column("timestamp_unix_ms")?.i64()?.get(close.len() - 1).unwrap_or(0);
///
///         // Simple logic: Buy if price > 100
///         if last_price > 100.0 {
///             Ok(vec![Signal {
///                 signal_type: SignalType::Entry,
///                 symbol: "TEST".to_string(),
///                 side: "buy".to_string(),
///                 size_hint: "1.0".to_string(),
///                 confidence: 1.0,
///                 stop_loss: None,
///                 take_profit: None,
///                 reason: "Price > 100".to_string(),
///                 timestamp_ms: last_ts,
///             }])
///         } else {
///             Ok(vec![])
///         }
///     }
///
///     async fn update_params(&mut self, _params: serde_json::Value) -> Result<()> {
///         Ok(())
///     }
/// }
/// ```
#[async_trait]
pub trait Strategy: Send + Sync {
    /// Returns the unique name of the strategy.
    fn name(&self) -> &str;

    /// Returns the type/category of the strategy.
    ///
    /// This is used to apply specific filtering rules (e.g., Mean Reversion strategies
    /// shouldn't buy overbought assets, while Trend/Momentum strategies can).
    fn strategy_type(&self) -> StrategyType {
        // Default to TrendFollowing to be safe, but implementers should override.
        StrategyType::TrendFollowing
    }

    /// Generates trading signals based on the provided market data.
    ///
    /// # Arguments
    ///
    /// * `data` - A Polars `DataFrame` containing OHLCV data. Columns should include
    ///            "open", "high", "low", "close", "volume", and "timestamp".
    async fn generate_signals(&self, data: &DataFrame) -> Result<Vec<Signal>>;

    /// Updates the strategy parameters dynamically.
    ///
    /// # Arguments
    ///
    /// * `params` - A JSON object containing the new configuration.
    async fn update_params(&mut self, params: serde_json::Value) -> Result<()>;
}

/// A marker trait for strategy configuration structs.
pub trait StrategyConfig: Send + Sync {
    // Marker trait for strategy configuration
}
